import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {openDatabase,ensureShift} from '../database.mjs';import {discover,remember,uniqueNotes} from '../memory.mjs';import {questionsFor} from '../questions.mjs';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
function seed(db){ensureShift(db,'2030-01-01');db.prepare('INSERT INTO notes(id,day,body,kind,created) VALUES (?,?,?,?,?)').run('source-1','2030-01-01','Chicory barely enough.\nMore peaches than we need.\nLate walk-ins.','imported','2030-01-01T20:00:00Z')}
test('journal creates branching questions, evidence ignores duplicate pasted text and expectations',()=>{const db=openDatabase(':memory:');seed(db);ensureShift(db,'2030-01-02');db.prepare("UPDATE shifts SET phase='opening' WHERE day=?").run('2030-01-02');assert.equal(questionsFor(db,'2030-01-02')[0].id,'chicory_prep');db.prepare("UPDATE shifts SET phase='live' WHERE day=?").run('2030-01-02');db.prepare('INSERT INTO answers VALUES (?,?,?,?,?,?,?)').run('answer1','2030-01-02','pace','How is service?','In a rush','observation','2030-01-02T20:00:00Z');assert(questionsFor(db,'2030-01-02').some(q=>q.id==='rush_start'));
const rows=[{id:'a',day:'2030-01-01',body:'Chicory ran out',kind:'imported'},{id:'b',day:'2030-01-02',body:'Chicory ran out  ',kind:'imported'},{id:'c',day:'2030-01-03',body:'Chicory might be tight',kind:'expectation'}];assert.equal(uniqueNotes(rows).length,2);assert.deepEqual(discover(rows)[0].evidence,['a']);const i=remember(db,'2030-01-02');assert(db.prepare('SELECT id FROM insights WHERE id=?').get(i.id));db.close()});
test('local API persists answers, custom questions, changes, notes and feedback across restart',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'stories-test-'));const db=openDatabase(path.join(dir,'stories.sqlite'));seed(db);db.close();let child;
 const start=async()=>{child=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,STORIES_DATA_DIR:dir,STORIES_PORT:'4189',OPENAI_API_KEY:''},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Startup timed out')),8000);child.stdout.on('data',d=>{if(String(d).includes('ready at')){clearTimeout(timer);resolve()}});child.once('exit',c=>{clearTimeout(timer);reject(Error('Server exit '+c))})});};
 const stop=()=>new Promise(resolve=>{if(!child||child.exitCode!==null)return resolve();child.once('exit',resolve);child.kill('SIGINT')});t.after(async()=>{await stop();fs.rmSync(dir,{recursive:true,force:true})});await start();let html=await (await fetch('http://127.0.0.1:4189')).text(),token=html.match(/name="app-token" content="([^"]+)"/)[1];
 const call=async(route,data)=>{const r=await fetch('http://127.0.0.1:4189/api/'+route+(data?'':'?day=2030-01-02'),{method:data?'POST':'GET',headers:{'x-app-token':token,origin:'http://127.0.0.1:4189','content-type':'application/json'},body:data?JSON.stringify({day:'2030-01-02',...data}):undefined});return {status:r.status,data:await r.json()}};
 assert.equal((await call('shift',{action:'start',expected:-1})).status,400);
 let r=await call('shift',{action:'start',expected:40});assert.equal(r.status,200);assert.equal(r.data.questions[0].id,'chicory_prep');
 const answer={id:'answer-safe',questionId:'chicory_prep',answer:'Might be tight'};assert.equal((await call('answer',answer)).status,200);assert.equal((await call('answer',answer)).status,200);assert.equal((await call('state')).data.answers.length,1);
 await call('shift',{action:'open',opening:''});await call('answer',{id:'pace1',questionId:'pace',answer:'In a rush'});r=await call('state');assert(r.data.questions.some(q=>q.id==='rush_start'));
 await call('question',{title:'How is the focaccia?',options:['Fine','Watch it','Needs attention'],phase:'live'});r=await call('state');const custom=r.data.questions.find(q=>q.title==='How is the focaccia?');assert(custom);await call('answer',{id:'custom-answer',questionId:custom.id,answer:'Needs attention'});
 const n={id:'note-safe',body:'A useful additional observation.'};await call('note',n);await call('note',n);r=await call('state');assert.equal(r.data.notes.filter(n=>n.id==='note-safe').length,1);
 const i=r.data.insights[0];await call('feedback',{id:i.id,value:'helpful'});const exported=(await call('export')).data;assert.equal(exported.questionTemplates.length,1);assert.equal(exported.productChanges.length,1);assert(exported.answers.some(a=>a.id==='custom-answer'));assert.equal(exported.feedback[0].value,'helpful');assert(!JSON.stringify(exported).includes('openaiKey'));
 assert.equal((await call('think',{})).status,503);await stop();await start();html=await (await fetch('http://127.0.0.1:4189')).text();token=html.match(/name="app-token" content="([^"]+)"/)[1];r=await call('state');assert(r.data.notes.some(n=>n.id==='note-safe'));assert(r.data.answers.some(a=>a.id==='custom-answer'));assert.equal(r.data.productChanges.length,1);assert(fs.readdirSync(path.join(dir,'backups')).some(n=>n.endsWith('.sqlite')));
 const denied=await fetch('http://127.0.0.1:4189/api/state');assert.equal(denied.status,403);
});
